##############################################################################
# Cactus Theme Configuration
# This file overrides the default theme configuration
##############################################################################

# Link to your GitHub profile
projects_url: https://github.com/zhengzhenyu

# Navigation menu
nav:
  home: /
  about: /about/
  articles: /archives/
  projects: https://github.com/zhengzhenyu

# Social media links
social_links:
  -
    icon: github
    link: https://github.com/zhengzhenyu
  -
    icon: mail
    link: mailto:zhengzhenyu.here@gmail.com
  -
    icon: rss
    link: /atom.xml

# Show tag cloud on index page
tags_overview: true

# Recent posts on index page
posts_overview:
  show_all_posts: false
  post_count: 5
  sort_updated: true

# Archive settings
archive:
  sort_updated: true

# Show last modification date on posts
post:
  show_updated: true

# Copyright years
copyright:
  start_year: 2024
  end_year:

# Logo configuration
logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false
  grayout: true

# Color scheme: 'dark', 'light', 'classic', 'white'
colorscheme: dark

# Page width in rem units
page_width: 48

# Enable RSS feed
rss: /atom.xml

# Open Graph settings for social media sharing
open_graph:
  fb_app_id:
  fb_admins:
  twitter_id:
  google_plus:

# Enable MathJax for mathematical formulas
mathjax:
  enabled: false

# Utterances comments (GitHub-based comments)
utterances:
  enabled: true
  repo: zhengzhenyu/zhengzhenyu.github.io
  issue_term: pathname
  label: Comment
  theme: github-dark

# Google Analytics (optional - fill in if needed)
google_analytics:
  enabled: false
  id:

# CDN configuration
cdn:
  enable: true
  jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  clipboard: https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.7/clipboard.min.js
  font_awesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
  justified_gallery_css: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/css/justifiedGallery.min.css
  justified_gallery_js: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
